import { Form } from '@shared/components/form/@types/form';
import { getNames } from 'i18n-iso-countries';

export const CaregiversPatientForm: Form = {
  submitButtonText: 'Kaydet',
  editButtonText: 'Düzenle',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'relation',
          title: 'Hasta ile İlişki',
          label: 'İlişki',
          translationPath: 'forms.patients.relation',
          description: 'İlişkiyi girin',
          type: 'select',
          options: [
            { label: 'Anne', value: 'Mother' },
            { label: 'Baba', value: 'Father' },
            { label: 'Büyükanne/Büyükbaba', value: 'Grandparent' },
            { label: 'Amca/Teyze/Dayı/Hala', value: 'Uncle/Aunt' },
            { label: 'Geniş Aile', value: 'Extended Family' },
            { label: 'Yasal Vasi', value: 'Legal Guardian' },
            { label: 'Aile Doktoru', value: 'Family Doctor' },
            { label: 'Dış Pediatrist', value: 'External Paediatrician' },
            { label: 'Dış Psikoterapist', value: 'External Psychotherapist' },
            { label: 'Dış Psikolog', value: 'External Psychologist' },
            { label: 'Dış Sosyal Hizmet Uzmanı', value: 'External Social Worker' },
            { label: 'Dış Hemşire', value: 'External Nurse' },
            { label: 'Acil Servis', value: 'Emergency Department' },
            { label: 'Arkadaş', value: 'Friend' },
            { label: 'Komşu', value: 'Neighbour' },
            { label: 'Öğretmen', value: 'Teacher' },
            { label: 'Okul Temsilcisi', value: 'School Representative' },
            { label: 'Danışman', value: 'Advisor' },
            { label: 'Yasal Danışman', value: 'Legal Advisor' },
            { label: 'Yardımcı', value: 'Assistance' },
            { label: 'Gözetmen', value: 'Supervisor' },
            { label: 'Diğer', value: 'Other' },
          ],
          validationMessage: 'lütfen ilişkiyi girin',
          isRequired: true,
          span: 24,
        },
        {
          value: '',
          name: 'emergency',
          title: 'Acil Durum İletişimi',
          label: 'Acil Durum',
          translationPath: 'forms.patients.emergency',
          type: 'radio',
          options: [
            { label: 'Evet', value: true },
            { label: 'Hayır', value: false },
          ],
          validationMessage: 'lütfen acil durum bilgisini girin',
          isRequired: false,
          span: 24,
        },
        {
          value: '',
          name: 'note',
          title: 'Not',
          label: 'Not',
          translationPath: 'forms.patients.note',
          description: 'Not girin',
          type: 'textArea',
          validationMessage: 'lütfen not girin',
          isRequired: false,
          span: 24,
        },
        {
          value: '',
          name: 'phone',
          title: 'Telefon',
          label: 'Telefon',
          // disabled: true,
          translationPath: 'forms.patients.phone',
          description: 'Telefon numarasını girin',
          type: 'text',
          validationMessage: 'lütfen telefon numarasını girin',
          isRequired: true,
          span: 13,
        },
        {
          value: '',
          name: 'firstName',
          title: 'Ad',
          label: 'Ad',
          // disabled: true,
          translationPath: 'forms.patients.firstName',
          description: 'Adı girin',
          type: 'text',
          validationMessage: 'lütfen adı girin',
          isRequired: true,
          span: 12,
        },
        {
          value: '',
          name: 'middleName',
          title: 'İkinci Ad',
          label: 'İkinci Ad',
          // disabled: true,
          translationPath: 'forms.patients.middleName',
          description: 'İkinci adı girin',
          type: 'text',
          validationMessage: 'lütfen ikinci adı girin',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'lastName',
          title: 'Soyad',
          label: 'Soyad',
          // disabled: true,
          translationPath: 'forms.patients.lastName',
          description: 'Soyadı girin',
          type: 'text',
          validationMessage: 'lütfen soyadı girin',
          isRequired: true,
          span: 12,
        },
        {
          value: '',
          name: 'email',
          title: 'E-posta',
          label: 'E-posta',
          // disabled: true,
          translationPath: 'forms.patients.email',
          description: 'E-posta adresini girin',
          type: 'text',
          validationMessage: 'lütfen e-posta adresini girin',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'street',
          title: 'Sokak',
          label: 'Sokak',
          // disabled: true,
          translationPath: 'forms.patients.street',
          description: 'Sokak adını girin',
          type: 'text',
          validationMessage: 'lütfen sokak adını girin',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'number',
          title: 'Numara',
          label: 'Numara',
          // disabled: true,
          translationPath: 'forms.patients.number',
          description: 'Numarayı girin',
          type: 'text',
          validationMessage: 'lütfen numarayı girin',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'apartment',
          title: 'Daire',
          label: 'Daire',
          // disabled: true,
          translationPath: 'forms.patients.apartment',
          description: 'Daire numarasını girin',
          type: 'text',
          validationMessage: 'lütfen daire numarasını girin',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'place',
          title: 'Yer',
          label: 'Yer',
          // disabled: true,
          translationPath: 'forms.patients.place',
          description: 'Yeri girin',
          type: 'text',
          validationMessage: 'lütfen yeri girin',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'postalCode',
          title: 'Posta Kodu',
          label: 'Posta Kodu',
          // disabled: true,
          translationPath: 'forms.patients.postalCode',
          description: 'Posta kodunu girin',
          type: 'text',
          validationMessage: 'lütfen posta kodunu girin',
          isRequired: false,
          span: 12,
        },
        {
          value: '',
          name: 'country',
          title: 'Ülke',
          label: 'Ülke',
          // disabled: true,
          translationPath: 'forms.patients.country',
          description: 'Ülkeyi girin',
          type: 'select',
          validationMessage: 'lütfen ülkeyi girin',
          isRequired: false,
          span: 12,
          options: Object.entries(getNames('en', { select: 'official' })).map(([value, label]) => ({ label, value })),
        },
      ],
    },
  ],
};
