import { Form } from '@shared/components/form/@types/form';

export const InformantForm: Form = {
  submitButtonText: 'Bilgi Vereni Gönder',
  editButtonText: 'Bilgi Vereni Gönder',
  submitButtonClass: 'full-width',
  groups: [
    {
      fields: [
        {
          value: '',
          name: 'firstName',
          title: 'Ad',
          label: 'Ad',
          description: 'adı girin',
          type: 'text',
          validationMessage: 'lütfen adı girin',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'middleName',
          title: 'İkinci Ad',
          label: 'İkinci Ad',
          description: 'ikinci adı girin',
          type: 'text',
          validationMessage: 'lütfen ikinci adı girin',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'lastName',
          title: 'Soyad',
          label: 'Soyad',
          description: 'soyadı girin',
          type: 'text',
          validationMessage: 'lütfen soyadı girin',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'phone',
          title: 'Telefon',
          label: 'Telefon',
          description: 'telefonu girin',
          type: 'text',
          validationMessage: 'lütfen telefonu girin',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'email',
          title: 'E-posta',
          label: 'E-posta',
          description: 'e-postayı girin',
          type: 'text',
          validationMessage: 'lütfen e-postayı girin',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'address',
          title: 'Adres',
          label: 'Adres',
          description: 'adresi girin',
          type: 'text',
          validationMessage: 'lütfen adresi girin',
          isRequired: false,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'patientId',
          title: 'Hasta',
          label: 'Hasta',
          description: 'hasta seçin',
          type: 'search',
          validationMessage: 'lütfen hasta seçin',
          isRequired: true,
          span: 24,
          options: [],
        },
        {
          value: '',
          name: 'relationshipTypeId',
          title: 'İlişki Türü',
          label: 'İlişki Türü',
          description: 'ilişki türünü seçin',
          type: 'select',
          validationMessage: 'lütfen ilişki türünü seçin',
          isRequired: false,
          span: 24,
          options: [],
        },
      ],
    },
  ],
};
