import { Form } from '@shared/components/form/@types/form';
import { Field } from '@shared/components/form/@types/field';

const informationFields: Field[] = [
  {
    value: '',
    name: 'firstName',
    title: 'Ad',
    label: 'Ad',
    translationPath: 'forms.patients.firstName',
    description: 'forms.patients.description',
    type: 'text',
    validationMessage: 'forms.patients.validationMessage',
    isRequired: true,
    span: 8,
  },
  {
    value: '',
    name: 'middleName',
    title: 'İkinci Ad',
    label: 'İkinci Ad',
    translationPath: 'forms.patients.middleName',
    description: 'forms.patients.descriptionEnterMiddleName',
    type: 'text',
    validationMessage: 'forms.patients.validationMessageMiddleName',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'lastName',
    title: 'Soyad',
    label: 'Soyad',
    translationPath: 'forms.patients.lastName',
    description: 'forms.patients.descriptionEnterLastName',
    type: 'text',
    validationMessage: 'forms.patients.validationMessageLastName',
    isRequired: true,
    span: 8,
  },
  {
    value: '',
    name: 'medicalRecordNo',
    title: 'Kimlik No',
    label: 'Tıbbi kayıt numarası',
    translationPath: 'forms.patients.id',
    description: 'forms.patients.descriptionId',
    type: 'text',
    validationMessage: 'forms.patients.validationMessageId',
    isRequired: true,
    span: 8,
  },
  {
    value: '',
    title: 'Doğum Tarihi',
    name: 'birthDate',
    label: 'Doğum Tarihi',
    translationPath: 'forms.patients.birthDate',
    description: 'forms.patients.descriptionBirthDate',
    type: 'date',
    validationMessage: 'forms.patients.validationMessageBirth',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'gender',
    title: 'Cinsiyet',
    label: 'Cinsiyet',
    translationPath: 'tables.patients.gender',
    description: 'tables.patients.selectGender',
    type: 'select',
    validationMessage: 'forms.patients.validationMessageGender',
    isRequired: false,
    options: [
      { label: 'forms.patients.gender.male', value: 'male' }, 
      { label: 'forms.patients.gender.female', value: 'female' },
      { label: 'forms.patients.gender.other', value: 'other' },
    ],
    span: 8,
  },
  {
    value: '',
    name: 'statusId',
    title: 'Durum',
    label: 'Durum',
    translationPath: 'forms.patients.status',
    description: 'forms.patients.descriptionStatus',
    type: 'select',
    validationMessage: 'forms.patients.validationMessageStatus',
    isRequired: false,
    options: [],
    span: 8,
  },
];

const departmentsField: Field = {
  value: '',
  name: 'departmentIds',
  title: 'Departman',
  label: 'Departman',
  translationPath: 'forms.patients.department',
  description: 'forms.patients.descriptionSelect',
  type: 'select',
  validationMessage: 'forms.patients.validationMessageSelect',
  isRequired: true,
  options: [],
  span: 8,
};

const addressFields: Field[] = [
  {
    value: '',
    name: 'addressStreet',
    title: 'Cadde',
    label: 'Cadde',
    translationPath: 'forms.patients.street',
    description: 'forms.patients.descriptionStreetName',
    type: 'text',
    validationMessage: 'forms.patients.validationMessageStreet',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressNumber',
    title: 'Numara',
    label: 'Numara',
    translationPath: 'forms.patients.addressNumber',
    description: 'forms.patients.descriptionApartment',
    type: 'text',
    validationMessage: 'forms.patients.validationMessagApartment',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressApartment',
    title: 'Daire',
    label: 'Daire',
    translationPath: 'forms.patients.addressApartment',
    description: 'forms.patients.descriptionApartment',
    type: 'text',
    validationMessage: 'forms.patients.validationMessagApartment',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressPlace',
    title: 'Yer',
    label: 'Yer',
    translationPath: 'forms.patients.addressPlace',
    description: 'forms.patients.descriptionEnterPlace',
    type: 'text',
    validationMessage: 'forms.patients.validationMessagePlace',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressPostalCode',
    title: 'Posta Kodu',
    label: 'Posta Kodu',
    translationPath: 'forms.patients.addressPostalCode',
    description: 'forms.patients.descriptionEnterPostal',
    type: 'text',
    validationMessage: 'forms.patients.validationMessagePostal',
    isRequired: false,
    options: [],
    span: 8,
  },
  {
    value: '',
    name: 'addressCountryCode',
    title: 'Ülke',
    label: 'Ülke',
    translationPath: 'forms.patients.addressCountryCode',
    description: 'forms.patients.descriptionEnterCountry',
    type: 'select',
    validationMessage: 'forms.patients.validationMessageCountry',
    isRequired: false,
    span: 8,
    options: [
      { label: 'Turkey', value: 'TR' },
      { label: 'United States', value: 'US' },
      { label: 'Germany', value: 'DE' },
      { label: 'United Kingdom', value: 'GB' },
    ],
  },
];

const contactFields: Field[] = [
  {
    value: '',
    name: 'email',
    title: 'E-posta Adresi',
    label: 'E-posta Adresi',
    translationPath: 'forms.patients.email',
    description: 'forms.patients.descriptionEnterEmail',
    type: 'text',
    validationMessage: 'forms.patients.validationMessageEmail',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'phone',
    title: 'Telefon',
    label: 'Telefon',
    translationPath: 'forms.patients.phone',
    description: 'forms.patients.descriptionPhone',
    type: 'text',
    validationMessage: 'forms.patients.validationMessagePhone',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'phone2',
    title: 'Alternatif Telefon',
    label: 'Alternatif Telefon',
    translationPath: 'forms.patients.phone2',
    description: 'forms.patients.descriptionPhone2',
    type: 'text',
    validationMessage: 'forms.patients.validationMessagePhone2',
    isRequired: false,
    span: 8,
  },
];

const emergencyContactFields: Field[] = [
  {
    value: '',
    name: 'firstName',
    title: 'Ad',
    label: 'Ad',
    translationPath: 'forms.patients.firstName',
    description: 'forms.patients.descriptionContactName',
    type: 'text',
    validationMessage: 'forms.patients.validationContactName',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'middleName',
    title: 'İkinci Ad',
    label: 'İkinci Ad',
    translationPath: 'forms.patients.middleName',
    description: 'forms.patients.descriptionMiddleName',
    type: 'text',
    validationMessage: 'forms.patients.validationMiddleName',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'lastName',
    title: 'Soyad',
    label: 'Soyad',
    translationPath: 'forms.patients.lastName',
    description: 'forms.patients.descriptionLastName',
    type: 'text',
    validationMessage: 'forms.patients.validationLastName',
    isRequired: false,
    span: 8,
  },
  {
    value: '',
    name: 'email',
    title: 'E-posta',
    label: 'E-posta',
    translationPath: 'forms.patients.email',
    description: 'forms.patients.descriptionEmail',
    type: 'text',
    validationMessage: 'forms.patients.validationEmail',
    isRequired: false,
    span: 12,
  },
  {
    value: '',
    name: 'phone',
    title: 'Telefon',
    label: 'Telefon',
    translationPath: 'forms.patients.phone',
    description: 'forms.patients.descriptionContact',
    type: 'text',
    validationMessage: 'forms.patients.validationContact',
    isRequired: false,
    span: 12,
  },
];

const getForm = (createMode: boolean): Form => {
  return {
    submitButtonText: 'forms.patients.savePatient2',
    editButtonText: 'Hastayı Düzenle',
    submitButtonClass: 'right-align-submit',
    groups: [
      {
        title: 'Hasta Bilgileri',
        translationPath: 'forms.patients.patientInformation',
        fields: createMode ? [...informationFields, departmentsField] : informationFields,
      },
      {
        title: 'Hasta Adresi',
        translationPath: 'forms.patients.patientAddress',
        fields: addressFields,
      },
      {
        title: 'Hasta İletişim',
        translationPath: 'forms.patients.patientContact',
        fields: contactFields,
      },
      {
        title: 'Acil Durum İletişimleri',
        translationPath: 'forms.patients.emergency',
        fields: [{
          value: '',
          name: 'emergencyContacts',
          title: 'Acil Durum İletişimi',
          label: 'Acil Durum İletişimi',
          translationPath: 'forms.patients.emergencyContact',
          description: 'forms.patients.addEmergencyContact',
          type: 'array',
          validationMessage: 'forms.patients.validationEmergencyContact',
          isRequired: false,
          span: 24,
          rows: [],
          children: emergencyContactFields
        }]
      }
    ]
  };
};

export const PatientCreateForm: Form = {
  submitButtonText: 'Hastayı Kaydet',
  submitButtonClass: 'full-width',
  groups: [
    {
      title: 'Hasta Bilgileri',
      translationPath: 'forms.patients.patientInformation',
      fields: [
        ...informationFields,
        departmentsField,
        ...addressFields,
      ],
    },
    {
      title: 'Hasta İletişim',
      translationPath: 'forms.patients.patientContact',
      fields: contactFields,
    },
    {
      title: 'Acil Durum İletişimi',
      translationPath: 'forms.patients.emergency',
      fields: [{
        value: '',
        name: 'emergencyContacts',
        title: 'Acil Durum İletişimi',
        label: 'Acil Durum İletişimi',
        translationPath: 'forms.patients.emergencyContact',
        description: 'forms.patients.addEmergencyContact',
        type: 'array',
        validationMessage: 'forms.patients.validationEmergencyContact',
        isRequired: false,
        span: 24,
        rows: [],
        children: emergencyContactFields
      }]
    }
  ]
};

export const PatientUpdateForm = getForm(false);
